### ISSUE TITLE
cannot launch version 0.3.0

### ISSUE THREAD

**Issue by jeekajoo** [frankrousseau/kyou#9]
Hi,
I'm using
Data System: 2.0.8
Proxy: 2.1.3
Home: 2.0.11
Controller: 2.0.31
Kyou: 0.3.0

Log:
```javascript
module.js:340
    throw err;
          ^
Error: Cannot find module 'request-json-light/node_modules/form-data'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/cozy/apps/kyou/node_modules/cozydb/lib/cozymodel.js:33:14)
    at Object.<anonymous> (/usr/local/cozy/apps/kyou/node_modules/cozydb/lib/cozymodel.js:336:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
Error: Cannot find module 'request-json-light/node_modules/form-data'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/cozy/apps/kyou/node_modules/cozydb/lib/cozymodel.js:33:14)
    at Object.<anonymous> (/usr/local/cozy/apps/kyou/node_modules/cozydb/lib/cozymodel.js:336:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
```
Thanks 
J.

**Comment by frankrousseau** [comment]
Thank you for reporting @jeekajoo. Can you try to uninstall/install the application. It looks like the node package manager failed to grab all the dependencies.

**Comment by jeekajoo** [comment]
I already tried it. no effect.
thanks

**Comment by frankrousseau** [comment]
I can't reproduce. Can you tell me more about your setup (distribution, hardware)? Do you have available memory? Do you have available disk space?

**Comment by jeekajoo** [comment]
debian jessie, cozy official debian package, enough disk, enough ram.
maybe problem is related to https://github.com/cozy/cozy-proxy/issues/180#issuecomment-143590641

**Comment by frankrousseau** [comment]
What is your version of Node.js?

**Comment by jeekajoo** [comment]
3.3.4 but I reverted to 1.4.21 (debian jessie's version) and it works

**Comment by frankrousseau** [comment]
Ok we will handle soon the port to a more recent version of Node. It mainly fail because of the dependency you mention.
